services:
  flutter:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    platform: linux/amd64
    # network_mode: "host"
    working_dir: /workspace
    volumes:
      - .:/workspace
      - flutter-pub-cache:/root/.pub-cache
      - gradle-cache:/root/.gradle
    environment:
      - DISPLAY=novnc:0.0
    stdin_open: true
    tty: true
    command: sleep infinity
  novnc:
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - DISPLAY_MODE=remote
      - RUN_XTERM=no
      - RUN_FLUXBOX=yes
    ports:
      - "8104:8080"
    command: ["/bin/sh", "-c", "sed -i \"s/UI.initSetting('resize', 'off');/UI.initSetting('resize', 'scale');/\" /usr/share/novnc/app/ui.js && /app/entrypoint.sh"]

volumes:
  flutter-pub-cache:
  gradle-cache:
